name: Keep Backend Alive
on:
  schedule:
    # S'ex√©cute toutes les 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Permet de le lancer manuellement pour tester

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: |
          curl -f https://greeting-backend-n0f1.onrender.com/api/actuator/health || echo "Waking up..."