name: CI/CD Pipeline
on:
  push:
    branches: [ test, preprod, main ]

jobs:
  audit-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      # Indique au robot d'entrer dans le dossier greetingApp pour compiler
      - name: Build & Test Backend
        run: |
          chmod +x greetingApp/mvnw
          ./greetingApp/mvnw -f greetingApp/pom.xml clean package

  deploy:
    needs: audit-backend
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}